//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("libreriaModel", "FK__libros__idTema__0519C6AF", "temas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication1.temas), "libros", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.libros), true)]
[assembly: EdmRelationshipAttribute("libreriaModel", "FK__ventas__idLibro__060DEAE8", "libros", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication1.libros), "ventas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.ventas), true)]

#endregion

namespace WebApplication1
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class libreriaEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto libreriaEntities usando la cadena de conexión encontrada en la sección 'libreriaEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public libreriaEntities() : base("name=libreriaEntities", "libreriaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto libreriaEntities.
        /// </summary>
        public libreriaEntities(string connectionString) : base(connectionString, "libreriaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto libreriaEntities.
        /// </summary>
        public libreriaEntities(EntityConnection connection) : base(connection, "libreriaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<clientes> clientes
        {
            get
            {
                if ((_clientes == null))
                {
                    _clientes = base.CreateObjectSet<clientes>("clientes");
                }
                return _clientes;
            }
        }
        private ObjectSet<clientes> _clientes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<libros> libros
        {
            get
            {
                if ((_libros == null))
                {
                    _libros = base.CreateObjectSet<libros>("libros");
                }
                return _libros;
            }
        }
        private ObjectSet<libros> _libros;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<temas> temas
        {
            get
            {
                if ((_temas == null))
                {
                    _temas = base.CreateObjectSet<temas>("temas");
                }
                return _temas;
            }
        }
        private ObjectSet<temas> _temas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<ventas> ventas
        {
            get
            {
                if ((_ventas == null))
                {
                    _ventas = base.CreateObjectSet<ventas>("ventas");
                }
                return _ventas;
            }
        }
        private ObjectSet<ventas> _ventas;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet clientes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToclientes(clientes clientes)
        {
            base.AddObject("clientes", clientes);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet libros. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTolibros(libros libros)
        {
            base.AddObject("libros", libros);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet sysdiagrams. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet temas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTotemas(temas temas)
        {
            base.AddObject("temas", temas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ventas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToventas(ventas ventas)
        {
            base.AddObject("ventas", ventas);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="libreriaModel", Name="clientes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class clientes : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto clientes.
        /// </summary>
        /// <param name="usuario">Valor inicial de la propiedad usuario.</param>
        /// <param name="password">Valor inicial de la propiedad password.</param>
        /// <param name="email">Valor inicial de la propiedad email.</param>
        /// <param name="telefono">Valor inicial de la propiedad telefono.</param>
        public static clientes Createclientes(global::System.String usuario, global::System.String password, global::System.String email, global::System.String telefono)
        {
            clientes clientes = new clientes();
            clientes.usuario = usuario;
            clientes.password = password;
            clientes.email = email;
            clientes.telefono = telefono;
            return clientes;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usuario
        {
            get
            {
                return _usuario;
            }
            set
            {
                OnusuarioChanging(value);
                ReportPropertyChanging("usuario");
                _usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("usuario");
                OnusuarioChanged();
            }
        }
        private global::System.String _usuario;
        partial void OnusuarioChanging(global::System.String value);
        partial void OnusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                if (_password != value)
                {
                    OnpasswordChanging(value);
                    ReportPropertyChanging("password");
                    _password = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("password");
                    OnpasswordChanged();
                }
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private global::System.String _telefono;
        partial void OntelefonoChanging(global::System.String value);
        partial void OntelefonoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="libreriaModel", Name="libros")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class libros : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto libros.
        /// </summary>
        /// <param name="idLibro">Valor inicial de la propiedad idLibro.</param>
        /// <param name="idTema">Valor inicial de la propiedad idTema.</param>
        /// <param name="titulo">Valor inicial de la propiedad titulo.</param>
        /// <param name="precio">Valor inicial de la propiedad precio.</param>
        /// <param name="autor">Valor inicial de la propiedad autor.</param>
        public static libros Createlibros(global::System.Int32 idLibro, global::System.Int32 idTema, global::System.String titulo, global::System.Decimal precio, global::System.String autor)
        {
            libros libros = new libros();
            libros.idLibro = idLibro;
            libros.idTema = idTema;
            libros.titulo = titulo;
            libros.precio = precio;
            libros.autor = autor;
            return libros;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idLibro
        {
            get
            {
                return _idLibro;
            }
            set
            {
                if (_idLibro != value)
                {
                    OnidLibroChanging(value);
                    ReportPropertyChanging("idLibro");
                    _idLibro = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idLibro");
                    OnidLibroChanged();
                }
            }
        }
        private global::System.Int32 _idLibro;
        partial void OnidLibroChanging(global::System.Int32 value);
        partial void OnidLibroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTema
        {
            get
            {
                return _idTema;
            }
            set
            {
                OnidTemaChanging(value);
                ReportPropertyChanging("idTema");
                _idTema = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idTema");
                OnidTemaChanged();
            }
        }
        private global::System.Int32 _idTema;
        partial void OnidTemaChanging(global::System.Int32 value);
        partial void OnidTemaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String titulo
        {
            get
            {
                return _titulo;
            }
            set
            {
                OntituloChanging(value);
                ReportPropertyChanging("titulo");
                _titulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("titulo");
                OntituloChanged();
            }
        }
        private global::System.String _titulo;
        partial void OntituloChanging(global::System.String value);
        partial void OntituloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal precio
        {
            get
            {
                return _precio;
            }
            set
            {
                OnprecioChanging(value);
                ReportPropertyChanging("precio");
                _precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("precio");
                OnprecioChanged();
            }
        }
        private global::System.Decimal _precio;
        partial void OnprecioChanging(global::System.Decimal value);
        partial void OnprecioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String autor
        {
            get
            {
                return _autor;
            }
            set
            {
                OnautorChanging(value);
                ReportPropertyChanging("autor");
                _autor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("autor");
                OnautorChanged();
            }
        }
        private global::System.String _autor;
        partial void OnautorChanging(global::System.String value);
        partial void OnautorChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("libreriaModel", "FK__libros__idTema__0519C6AF", "temas")]
        public temas temas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<temas>("libreriaModel.FK__libros__idTema__0519C6AF", "temas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<temas>("libreriaModel.FK__libros__idTema__0519C6AF", "temas").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<temas> temasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<temas>("libreriaModel.FK__libros__idTema__0519C6AF", "temas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<temas>("libreriaModel.FK__libros__idTema__0519C6AF", "temas", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("libreriaModel", "FK__ventas__idLibro__060DEAE8", "ventas")]
        public EntityCollection<ventas> ventas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ventas>("libreriaModel.FK__ventas__idLibro__060DEAE8", "ventas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ventas>("libreriaModel.FK__ventas__idLibro__060DEAE8", "ventas", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="libreriaModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto sysdiagrams.
        /// </summary>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        /// <param name="principal_id">Valor inicial de la propiedad principal_id.</param>
        /// <param name="diagram_id">Valor inicial de la propiedad diagram_id.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="libreriaModel", Name="temas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class temas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto temas.
        /// </summary>
        /// <param name="idTema">Valor inicial de la propiedad idTema.</param>
        /// <param name="tema">Valor inicial de la propiedad tema.</param>
        public static temas Createtemas(global::System.Int32 idTema, global::System.String tema)
        {
            temas temas = new temas();
            temas.idTema = idTema;
            temas.tema = tema;
            return temas;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTema
        {
            get
            {
                return _idTema;
            }
            set
            {
                if (_idTema != value)
                {
                    OnidTemaChanging(value);
                    ReportPropertyChanging("idTema");
                    _idTema = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idTema");
                    OnidTemaChanged();
                }
            }
        }
        private global::System.Int32 _idTema;
        partial void OnidTemaChanging(global::System.Int32 value);
        partial void OnidTemaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tema
        {
            get
            {
                return _tema;
            }
            set
            {
                OntemaChanging(value);
                ReportPropertyChanging("tema");
                _tema = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tema");
                OntemaChanged();
            }
        }
        private global::System.String _tema;
        partial void OntemaChanging(global::System.String value);
        partial void OntemaChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("libreriaModel", "FK__libros__idTema__0519C6AF", "libros")]
        public EntityCollection<libros> libros
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<libros>("libreriaModel.FK__libros__idTema__0519C6AF", "libros");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<libros>("libreriaModel.FK__libros__idTema__0519C6AF", "libros", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="libreriaModel", Name="ventas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ventas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto ventas.
        /// </summary>
        /// <param name="idVentas">Valor inicial de la propiedad idVentas.</param>
        /// <param name="idLibro">Valor inicial de la propiedad idLibro.</param>
        /// <param name="cliente">Valor inicial de la propiedad cliente.</param>
        /// <param name="fecha">Valor inicial de la propiedad fecha.</param>
        public static ventas Createventas(global::System.Int32 idVentas, global::System.Int32 idLibro, global::System.String cliente, global::System.DateTime fecha)
        {
            ventas ventas = new ventas();
            ventas.idVentas = idVentas;
            ventas.idLibro = idLibro;
            ventas.cliente = cliente;
            ventas.fecha = fecha;
            return ventas;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idVentas
        {
            get
            {
                return _idVentas;
            }
            set
            {
                if (_idVentas != value)
                {
                    OnidVentasChanging(value);
                    ReportPropertyChanging("idVentas");
                    _idVentas = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idVentas");
                    OnidVentasChanged();
                }
            }
        }
        private global::System.Int32 _idVentas;
        partial void OnidVentasChanging(global::System.Int32 value);
        partial void OnidVentasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idLibro
        {
            get
            {
                return _idLibro;
            }
            set
            {
                OnidLibroChanging(value);
                ReportPropertyChanging("idLibro");
                _idLibro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idLibro");
                OnidLibroChanged();
            }
        }
        private global::System.Int32 _idLibro;
        partial void OnidLibroChanging(global::System.Int32 value);
        partial void OnidLibroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cliente
        {
            get
            {
                return _cliente;
            }
            set
            {
                OnclienteChanging(value);
                ReportPropertyChanging("cliente");
                _cliente = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cliente");
                OnclienteChanged();
            }
        }
        private global::System.String _cliente;
        partial void OnclienteChanging(global::System.String value);
        partial void OnclienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("libreriaModel", "FK__ventas__idLibro__060DEAE8", "libros")]
        public libros libros
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<libros>("libreriaModel.FK__ventas__idLibro__060DEAE8", "libros").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<libros>("libreriaModel.FK__ventas__idLibro__060DEAE8", "libros").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<libros> librosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<libros>("libreriaModel.FK__ventas__idLibro__060DEAE8", "libros");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<libros>("libreriaModel.FK__ventas__idLibro__060DEAE8", "libros", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
